language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
matrix:
  fast_finish: true
  allow_failures:
    - env: $TRAVIS_NODE_VERSION=10
    - env: $TRAVIS_NODE_VERSION=9
    - env: $TRAVIS_NODE_VERSION=8
    - env: $TRAVIS_NODE_VERSION=7
install: npm install
script:
  - npm run cli -- data impl results bench -r catmaid/CATMAID -b dev -t ./tmp/refImpl.js -d ./tmp/copiedData -l 1999 -f 0.89 -o ./tmp/newResults -n 10
notifications:
  email: false
